#!/usr/bin/env bash

TIME=$(date +%s)
OUTFILE="$HOME/public_html/hivemind/data/historical/$TIME.json"
LATEST="$HOME/public_html/hivemind/data/latest.json"

$(dirname $0)/../venv/bin/python census.py > "$OUTFILE"

if [ -s "$OUTFILE" ]; then
  cp "$OUTFILE" "$LATEST"
fi
