#!/usr/bin/env bash

TIME=`date +%s`

python census.py > ~/public_html/hivemind/data/historical/$TIME.json

cp ~/public_html/hivemind/data/historical/$TIME.json ~/public_html/hivemind/data/latest.json
